import UIKit

var sehir = "Adana"
var ulke = "Türkiye"
var telefon : Int = 5444545454
var postaKodu = 1010
var email : String = "davutkarakus3@gmail.com"
var meslek = "Mühendis"
var stokMiktari : Int = 12
var müsteriAdi = "Davut"
var bakiye : Double = 54.22
var dogumGunu = "07/11/1996"
var maas : Int = 12500
var medeniDurum : String = "Bekar"
var urunYorum = "Çok güzeldi"
var odemeTarihi = "15.04.2022"
var odeme = 43.76
var siparisAdedi = 3
var arabaModeli = "Ford"
var kitapAdi = "Sefiller"
var yayinlamaTarihi : String = "15.06.2010"
var indirimMiktari : Double = 0.32
var odaSayisi : Int = 6
var enlem = 2.75
var boylam = 3
var urunAdi : String = "Macbook"
var yemekFiyati : Double = 59.99
var marka : String = "Asus"
var muzikAdi = "Olur mu?"
var videoSuresi = 24.54
var urunPuani : Int = 5
var resimAdi : String = "Doğa Resmi"
var dosyaFormati = ".dll"
var renk : String = "kırmızı"
var renkKodu = "#324324324"
var telefonModeli = "Red-mi 9"
var ekranBoyutu = "13 inç"
var agirlik = 65
var ulusalGun = "19 Mayıs"
var tatilGunu = "Cumartesi,Pazar"
var rezervasyonTarihi = "04.01.2023"
var sokakAdi = "Menekşe Sokak"
var otobusHatti = "Balcalı-Barajyolu"
var kalanDakika = 39
var takipKodu = 123454223
var kuponSuresi = "12 Gün"
var kuponKodu = 4824324
var faturaAdresi = "Güzelyalı Mahallesi Çukurova/Adana"

